"""Sync src/porchlight/log.py to the AgentCore deploy zip VERBATIM.

§32a: The deploy copy at
  deploy/spike_b/porchlightspike/app/porchlight_spike/porchlight/log.py
is GENERATED by this script. Do not edit it directly; edits there are
overwritten on the next run.

The source of truth is src/porchlight/log.py. This script copies it
byte-for-byte so the redaction processor proven in unit tests is
identical to the one running in the deployed AgentCore runtime.

A companion test (tests/test_deploy_sync.py) asserts byte-identity in
the default test suite, so drift fails within one test run.

Usage:
    uv run python scripts/sync_deploy_log.py
"""

from __future__ import annotations

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

SOURCE = REPO_ROOT / "src" / "porchlight" / "log.py"
DEST = (
    REPO_ROOT
    / "deploy"
    / "spike_b"
    / "porchlightspike"
    / "app"
    / "porchlight_spike"
    / "porchlight"
    / "log.py"
)


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Source not found: {SOURCE}")

    DEST.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SOURCE, DEST)
    print(f"Synced: {SOURCE.relative_to(REPO_ROOT)} -> {DEST.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
